# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['Id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('GNR', models.AutoField(primary_key=True, serialize=False)),
                ('StartTime', models.DateField()),
                ('EndTime', models.DateField()),
                ('AmountReq', models.CharField(max_length=100)),
                ('AmountPaid', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=10)),
                ('Reason', models.CharField(max_length=1000)),
                ('BookingTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['GNR'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Status', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['Id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cost', models.CharField(max_length=40)),
                ('Status', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['Id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['Id'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='RoomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
